#!/bin/bash

#Cameron Deao
#CST-221
#Michael Landreth
#7/17/2020

#Global variables
checkCounter=0
totalTests=3
missingTests=0

echo "Password Strength Test!"
echo "PW Suggestion: Minimum 8 characters, 1 numeric character, and 1 non-alphabetic character."

#Hiding input characters while reading input.
read -s -p "Please enter a password: " pwInput

#Formatting for the console.
echo " "

#Getting length of input.
length=${#pwInput}
#Checking length of input.
if [ $length -lt 8 ]
then
	echo 'Password should contain 8 characters!'
else
	#Incrementing counter.
	let "checkCounter++"
fi

#Checking if numeric characters exist within input.
if [[ $pwInput =~ [0-9] ]];
then
	let "checkCounter++"
else
	echo 'Password does not contain a number!'
fi

#Checking if non-alphabetic characters exist within input.
if [[ $pwInput == *['!'@#/$%^\&*()_+=]* ]];
then
	let "checkCounter++"
else
	echo 'Password does not contain a special character!'
fi

#Checking gobal counter against total tests.
if [ $checkCounter -eq 3 ]
then
	echo "You've input a strong password!"
else
	#Performing arithmetic to find total tests that failed.
	let "missingTests=totalTests-checkCounter"
	echo "You've input a weak password! $missingTests suggestions were missing!"
fi
